spring:
  mongodb:
    embedded:
      version: 4.4.9

  webflux:
    hiddenmethod:
      filter:
        enabled: true

  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: true

logging:
  level:
    org.springframework:
      amqp: DEBUG
      messaging: DEBUG
      data: DEBUG
    reactor: DEBUG
    com.js.hackingspringboot: DEBUG
