server:
  port: 9000

spring:
  rsocket:
    server:
      port: 8000
      transport: tcp

logging:
  level:
    com.js.hackingspringboot.reactive: DEBUG
    org.springframework.data: DEBUG
    reactor: DEBUG
    io.rsocket: DEBUG
